### PR TITLE
Add less task

### PR DESCRIPTION
**Pull request by clemensf**
- added less task to gulp "build" and "serve" task, using "gulp-less"
- based on "lint:sass", I also created a task "lint:less" using "gulp-lesshint", but it seems this is not working yet.
- fixed source directory for "sass" task
- fixed some indentations in index.js

### CODE REVIEW

**Comment by timomayer** [comment]
hey clemens thanks for you first PR 🥇 I highly appreciate it :)

We use a projectConfig.json in our projects where you can configure the build framework and which tasks you wanna use https://github.com/virtualidentityag/frontend-framework/blob/master/projectConfig.json
can you please make the less task configurable in the projectConfig with default to false cause sass is our default css preprocessor.

one other thought but thats not a technical one: can you imagine to switch to sass so we are streamlined in this technology over all VI projects? we did a less2sass conversion for another client and it is not that much afford...

**Comment by clemensf** [comment]
Hey timo,
thanx for your feedback! I also appreciate that indeed!
I will hav a look at the projectConfig.json, thanx for that hint.

I understand your goal of decreasing the number of technologies in our dev portfolio.
We discussed switching our project to sass, but did decide against it at least for now, because of the effort, testing etc.
Did you use an automatic conversion with some less2sass tool? That could help decrease the effort at least from a technical perspective. Testing would still be needed

**Comment by janrembold** [comment]
Hi Clemens,
many thanks also from me.

As Timo already mentioned, please add a "less" and a "sass" variable to the global config `global.tasks`. SASS should default to true and LESS to false. 

Also have a look at the corresponding if..else that is used to enable/disable the task itself. We would need the same logic in the sass task as well. Example is here: https://github.com/virtualidentityag/gulp-build-framework/blob/master/gulp/tasks/webpack.js#L14

If the task is disabled it throws a message, the linter and watch tasks are silently disabled.

**Comment by clemensf** [comment]
Thanks Jan, 
I added the sass and less options to config.js and less.js and sass.js tasks like suggested.
Also will state a pull request for frontend-framework projectConfig.js with these two options.

**Comment by clemensf** [comment]
sry, closed the pull request accidentally, reopened now.
@janrembold : please check and merge into virtualidentityag repo.

**Pull request merged**
